service: streamingStatusApi
frameworkVersion: "3"

custom:
  dotenv: ${file(./dotenv_loader.js)}

provider:
  name: aws
  deploymentMethod: direct
  runtime: python3.11
  region: eu-west-1
  versionFunctions: false
  architecture: "x86_64"
  environment:
    POWERTOOLS_SERVICE_NAME: ${self:service}
    OIDC_INTROSPECTION_ENDPOINT: ${self:custom.dotenv.OIDC_JWT_ISSUER_URL}/protocol/openid-connect/token/introspect
    STAGE: ${opt:stage}
  logs:
    httpApi: true
  httpApi:
    payload: "2.0"
    disableDefaultEndpoint: false
    cors:
      allowCredentials: true
      maxAge: 300
      allowedOrigins:
        - ${self:custom.dotenv.CORS_ALLOWED_ORIGIN}
    authorizers:
      # customJwtAuthorizer:
      #   type: request
      #   functionArn: arn:aws:lambda:eu-central-1:450869586150:function:jwt-authtoken-lambda
      jwtAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: ${self:custom.dotenv.OIDC_JWT_ISSUER_URL}
        audience:
          - ${self:custom.dotenv.OIDC_CLIENT_ID}
  iam:
    role:
      statements:
        # TODO convert to readonly on the required resources only for least-privileged permissions.
        # currently need permissions to query the iot fleet indexing and dynamodb for the device lodger
        - Effect: Allow
          Action: [iot:*, dynamodb:*, s3:*]
          Resource: "*"

package:
  individually: true

functions:
  devicesStatusApi:
    handler: streaming_status.app.handler
    description: data streaming platform devices status API
    package:
      patterns:
        - "!**"
        - streaming_status/**
    environment: ${self:custom.dotenv}
    layers:
      # depends on the architecture
      - arn:aws:lambda:${aws:region}:017000801446:layer:AWSLambdaPowertoolsPythonV2:46
    events:
      - httpApi:
          authorizer:
            # TODO switch to using the custom authorizer, the default jwt authorizer doesn't validate the roles
            # or maybe use a scope instead of a role.
            name: jwtAuthorizer
          path: /api/{proxy+}
          method: "*"
      - httpApi:
          path: /api/{proxy+}
          method: OPTIONS

plugins:
  - serverless-python-requirements
  - serverless-offline
