name: Deploy IoT status api to development (staging) server

on:
    workflow_dispatch:
jobs:
    deploy:
        name: Deploy to Dev staging server
        runs-on: ubuntu-latest

        permissions:
            contents: read

        steps:
            - name: Set up python version and virtual environment
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.11' 

            - name: install dependencies
            - run: |
                npm install -g serverless
                npm install
                python -m venv .venv
                source .venv/bin/activate
                python -m pip install -r requirements/dev.txt
