name: Deploy IoT status api to development (staging) server

on:
    workflow_dispatch:
jobs:
    deploy:
        name: Deploy to Dev staging server
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read


        steps:
            - name: Commit the code to the workflow
              uses: actions/checkout@v4
            
            - name: Use the correct python version
              uses: actions/setup-python@v5
              with:
                python-version: '3.11' 

            - name: Install npm dependencies
              run: |
                npm install -g serverless
                npm install
            
            - name: Install python dependencies
              run: |      
                python -m pip install -r requirements/dev.txt
            
            - name: Authenticate AWS
              uses: aws-actions/configure-aws-credentials@v4.0.2
              with:
                aws-region: eu-west-1
                role-to-assume: ${{ secrets.ROLE_OIDC }}
            
            
            - name: Retrieve github secrets and set to environment
              uses: aws-actions/aws-secretsmanager-get-secrets@v2.0.1
              with: 
                secret-ids: |
                    test
                    # ${{ secrets.AWS_SECRET_ARN }}
            

